
# Consider dependencies only in project.
set(CMAKE_DEPENDS_IN_PROJECT_ONLY OFF)

# The set of languages for which implicit dependencies are needed:
set(CMAKE_DEPENDS_LANGUAGES
  )

# The set of dependency files which are needed:
set(CMAKE_DEPENDS_DEPENDENCY_FILES
  "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.cpp" "CMakeFiles/qcc.dir/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.cpp.o" "gcc" "CMakeFiles/qcc.dir/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.cpp.o.d"
  "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpParser/QSharpParser.cpp" "CMakeFiles/qcc.dir/antlr4cpp_generated_src/QSharpParser/QSharpParser.cpp.o" "gcc" "CMakeFiles/qcc.dir/antlr4cpp_generated_src/QSharpParser/QSharpParser.cpp.o.d"
  "/Users/kevinchau/qcc/src/qcc.cpp" "CMakeFiles/qcc.dir/src/qcc.cpp.o" "gcc" "CMakeFiles/qcc.dir/src/qcc.cpp.o.d"
  )

# Pairs of files generated by the same build rule.
set(CMAKE_MULTIPLE_OUTPUT_PAIRS
  "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.cpp" "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.interp"
  "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.h" "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.interp"
  "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.tokens" "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpLexer/QSharpLexer.interp"
  "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpParser/QSharpParser.cpp" "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpParser/QSharpParser.interp"
  "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpParser/QSharpParser.h" "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpParser/QSharpParser.interp"
  "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpParser/QSharpParser.tokens" "/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpParser/QSharpParser.interp"
  )


# Targets to which this target links which contain Fortran sources.
set(CMAKE_Fortran_TARGET_LINKED_INFO_FILES
  )

# Fortran module output directory.
set(CMAKE_Fortran_TARGET_MODULE_DIR "")
