# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# The generator used is:
set(CMAKE_DEPENDS_GENERATOR "Unix Makefiles")

# The top level Makefile was generated from the following files:
set(CMAKE_MAKEFILE_DEPENDS
  "CMakeCache.txt"
  "CMakeFiles/3.27.4/CMakeCCompiler.cmake"
  "CMakeFiles/3.27.4/CMakeCXXCompiler.cmake"
  "CMakeFiles/3.27.4/CMakeSystem.cmake"
  "CMakeLists.txt"
  "antlr4_runtime/tmp/antlr4_runtime-mkdirs.cmake"
  "cmake/ExternalAntlr4Cpp.cmake"
  "cmake/FindANTLR.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeCInformation.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeCXXInformation.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeCommonLanguageInclude.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeFindJavaCommon.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeGenericSystem.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeInitializeConfigs.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeLanguageInformation.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeSystemSpecificInformation.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Compiler/AppleClang-C.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Compiler/AppleClang-CXX.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Compiler/CMakeCommonCompilerMacros.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Compiler/Clang.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Compiler/GNU.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject/PatchInfo.txt.in"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject/RepositoryInfo.txt.in"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject/UpdateInfo.txt.in"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject/cfgcmd.txt.in"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject/gitclone.cmake.in"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject/gitupdate.cmake.in"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject/mkdirs.cmake.in"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/ExternalProject/shared_internal_commands.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/FindGit.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/FindJava.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/FindPackageMessage.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Platform/Apple-AppleClang-C.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Platform/Apple-AppleClang-CXX.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Platform/Apple-Clang-C.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Platform/Apple-Clang-CXX.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Platform/Apple-Clang.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Platform/Darwin-Initialize.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Platform/Darwin.cmake"
  "/usr/local/Cellar/cmake/3.27.4/share/cmake/Modules/Platform/UnixPaths.cmake"
  )

# The corresponding makefile is:
set(CMAKE_MAKEFILE_OUTPUTS
  "Makefile"
  "CMakeFiles/cmake.check_cache"
  )

# Byproducts of CMake generate step:
set(CMAKE_MAKEFILE_PRODUCTS
  "antlr4_runtime/tmp/antlr4_runtime-mkdirs.cmake"
  "antlr4_runtime/tmp/antlr4_runtime-gitclone.cmake"
  "antlr4_runtime/src/antlr4_runtime-stamp/antlr4_runtime-gitinfo.txt"
  "antlr4_runtime/tmp/antlr4_runtime-gitupdate.cmake"
  "antlr4_runtime/src/antlr4_runtime-stamp/antlr4_runtime-update-info.txt"
  "antlr4_runtime/src/antlr4_runtime-stamp/antlr4_runtime-patch-info.txt"
  "antlr4_runtime/tmp/antlr4_runtime-cfgcmd.txt"
  "antlr4_runtime/tmp/antlr4_runtime-cache-.cmake"
  "CMakeFiles/CMakeDirectoryInformation.cmake"
  )

# Dependency information for all targets:
set(CMAKE_DEPEND_INFO_FILES
  "CMakeFiles/antlr4_runtime.dir/DependInfo.cmake"
  "CMakeFiles/antlr4_runtime-build_static.dir/DependInfo.cmake"
  "CMakeFiles/antlr4_runtime-build_shared.dir/DependInfo.cmake"
  "CMakeFiles/qcc.dir/DependInfo.cmake"
  )
