# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# compile CXX with /Library/Developer/CommandLineTools/usr/bin/c++
CXX_DEFINES = -DANTLR4CPP_STATIC

CXX_INCLUDES = -I/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpLexer -I/Users/kevinchau/qcc/antlr4cpp_generated_src/QSharpParser -isystem /Users/kevinchau/qcc/antlr4_runtime/src/antlr4_runtime/runtime/Cpp/runtime/src

CXX_FLAGS = -std=gnu++17 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk

